/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedContractorsRouteImport } from './routes/_authenticated/contractors'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAiConversationsRouteImport } from './routes/_authenticated/ai-conversations'
import { Route as AuthenticatedAiAutomationsRouteImport } from './routes/_authenticated/ai-automations'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedActivityLogsRouteImport } from './routes/_authenticated/activity-logs'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations.index'
import { Route as AuthenticatedOrganizationsPermissionsRouteImport } from './routes/_authenticated/organizations.permissions'
import { Route as AuthenticatedOrganizationsMembersRouteImport } from './routes/_authenticated/organizations.members'
import { Route as AuthenticatedOrganizationsBrandingRouteImport } from './routes/_authenticated/organizations.branding'
import { Route as AuthenticatedOpsUsersRouteImport } from './routes/_authenticated/ops.users'
import { Route as AuthenticatedOpsBookingsRouteImport } from './routes/_authenticated/ops.bookings'
import { Route as AuthenticatedClientTendersRouteImport } from './routes/_authenticated/client.tenders'
import { Route as AuthenticatedClientSearchRouteImport } from './routes/_authenticated/client.search'
import { Route as AuthenticatedClientProfileRouteImport } from './routes/_authenticated/client.profile'
import { Route as AuthenticatedClientMessagesRouteImport } from './routes/_authenticated/client.messages'
import { Route as AuthenticatedClientFavoritesRouteImport } from './routes/_authenticated/client.favorites'
import { Route as AuthenticatedClientCalendarRouteImport } from './routes/_authenticated/client.calendar'
import { Route as AuthenticatedClientBookingsRouteImport } from './routes/_authenticated/client.bookings'
import { Route as AuthenticatedClientAiMatchRouteImport } from './routes/_authenticated/client.ai-match'
import { Route as AuthenticatedClientProvidersIdRouteImport } from './routes/_authenticated/client.providers.$id'
import { Route as AuthenticatedClientBookIdRouteImport } from './routes/_authenticated/client.book.$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractorsRoute =
  AuthenticatedContractorsRouteImport.update({
    id: '/contractors',
    path: '/contractors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiConversationsRoute =
  AuthenticatedAiConversationsRouteImport.update({
    id: '/ai-conversations',
    path: '/ai-conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAutomationsRoute =
  AuthenticatedAiAutomationsRouteImport.update({
    id: '/ai-automations',
    path: '/ai-automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityLogsRoute =
  AuthenticatedActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsPermissionsRoute =
  AuthenticatedOrganizationsPermissionsRouteImport.update({
    id: '/organizations/permissions',
    path: '/organizations/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsMembersRoute =
  AuthenticatedOrganizationsMembersRouteImport.update({
    id: '/organizations/members',
    path: '/organizations/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsBrandingRoute =
  AuthenticatedOrganizationsBrandingRouteImport.update({
    id: '/organizations/branding',
    path: '/organizations/branding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsUsersRoute = AuthenticatedOpsUsersRouteImport.update({
  id: '/ops/users',
  path: '/ops/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsBookingsRoute =
  AuthenticatedOpsBookingsRouteImport.update({
    id: '/ops/bookings',
    path: '/ops/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientTendersRoute =
  AuthenticatedClientTendersRouteImport.update({
    id: '/client/tenders',
    path: '/client/tenders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientSearchRoute =
  AuthenticatedClientSearchRouteImport.update({
    id: '/client/search',
    path: '/client/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientProfileRoute =
  AuthenticatedClientProfileRouteImport.update({
    id: '/client/profile',
    path: '/client/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMessagesRoute =
  AuthenticatedClientMessagesRouteImport.update({
    id: '/client/messages',
    path: '/client/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientFavoritesRoute =
  AuthenticatedClientFavoritesRouteImport.update({
    id: '/client/favorites',
    path: '/client/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientCalendarRoute =
  AuthenticatedClientCalendarRouteImport.update({
    id: '/client/calendar',
    path: '/client/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientBookingsRoute =
  AuthenticatedClientBookingsRouteImport.update({
    id: '/client/bookings',
    path: '/client/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientAiMatchRoute =
  AuthenticatedClientAiMatchRouteImport.update({
    id: '/client/ai-match',
    path: '/client/ai-match',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientProvidersIdRoute =
  AuthenticatedClientProvidersIdRouteImport.update({
    id: '/client/providers/$id',
    path: '/client/providers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientBookIdRoute =
  AuthenticatedClientBookIdRouteImport.update({
    id: '/client/book/$id',
    path: '/client/book/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ai-automations': typeof AuthenticatedAiAutomationsRoute
  '/ai-conversations': typeof AuthenticatedAiConversationsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contractors': typeof AuthenticatedContractorsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/client/ai-match': typeof AuthenticatedClientAiMatchRoute
  '/client/bookings': typeof AuthenticatedClientBookingsRoute
  '/client/calendar': typeof AuthenticatedClientCalendarRoute
  '/client/favorites': typeof AuthenticatedClientFavoritesRoute
  '/client/messages': typeof AuthenticatedClientMessagesRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/search': typeof AuthenticatedClientSearchRoute
  '/client/tenders': typeof AuthenticatedClientTendersRoute
  '/ops/bookings': typeof AuthenticatedOpsBookingsRoute
  '/ops/users': typeof AuthenticatedOpsUsersRoute
  '/organizations/branding': typeof AuthenticatedOrganizationsBrandingRoute
  '/organizations/members': typeof AuthenticatedOrganizationsMembersRoute
  '/organizations/permissions': typeof AuthenticatedOrganizationsPermissionsRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/client/book/$id': typeof AuthenticatedClientBookIdRoute
  '/client/providers/$id': typeof AuthenticatedClientProvidersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ai-automations': typeof AuthenticatedAiAutomationsRoute
  '/ai-conversations': typeof AuthenticatedAiConversationsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contractors': typeof AuthenticatedContractorsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/client/ai-match': typeof AuthenticatedClientAiMatchRoute
  '/client/bookings': typeof AuthenticatedClientBookingsRoute
  '/client/calendar': typeof AuthenticatedClientCalendarRoute
  '/client/favorites': typeof AuthenticatedClientFavoritesRoute
  '/client/messages': typeof AuthenticatedClientMessagesRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/search': typeof AuthenticatedClientSearchRoute
  '/client/tenders': typeof AuthenticatedClientTendersRoute
  '/ops/bookings': typeof AuthenticatedOpsBookingsRoute
  '/ops/users': typeof AuthenticatedOpsUsersRoute
  '/organizations/branding': typeof AuthenticatedOrganizationsBrandingRoute
  '/organizations/members': typeof AuthenticatedOrganizationsMembersRoute
  '/organizations/permissions': typeof AuthenticatedOrganizationsPermissionsRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/client/book/$id': typeof AuthenticatedClientBookIdRoute
  '/client/providers/$id': typeof AuthenticatedClientProvidersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authenticated/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/ai-automations': typeof AuthenticatedAiAutomationsRoute
  '/_authenticated/ai-conversations': typeof AuthenticatedAiConversationsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/contractors': typeof AuthenticatedContractorsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/client/ai-match': typeof AuthenticatedClientAiMatchRoute
  '/_authenticated/client/bookings': typeof AuthenticatedClientBookingsRoute
  '/_authenticated/client/calendar': typeof AuthenticatedClientCalendarRoute
  '/_authenticated/client/favorites': typeof AuthenticatedClientFavoritesRoute
  '/_authenticated/client/messages': typeof AuthenticatedClientMessagesRoute
  '/_authenticated/client/profile': typeof AuthenticatedClientProfileRoute
  '/_authenticated/client/search': typeof AuthenticatedClientSearchRoute
  '/_authenticated/client/tenders': typeof AuthenticatedClientTendersRoute
  '/_authenticated/ops/bookings': typeof AuthenticatedOpsBookingsRoute
  '/_authenticated/ops/users': typeof AuthenticatedOpsUsersRoute
  '/_authenticated/organizations/branding': typeof AuthenticatedOrganizationsBrandingRoute
  '/_authenticated/organizations/members': typeof AuthenticatedOrganizationsMembersRoute
  '/_authenticated/organizations/permissions': typeof AuthenticatedOrganizationsPermissionsRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/client/book/$id': typeof AuthenticatedClientBookIdRoute
  '/_authenticated/client/providers/$id': typeof AuthenticatedClientProvidersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/activity-logs'
    | '/ai-assistant'
    | '/ai-automations'
    | '/ai-conversations'
    | '/audit-logs'
    | '/bookings'
    | '/clients'
    | '/contractors'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/jobs'
    | '/notifications'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/tasks'
    | '/workflows'
    | '/invite/$token'
    | '/client/ai-match'
    | '/client/bookings'
    | '/client/calendar'
    | '/client/favorites'
    | '/client/messages'
    | '/client/profile'
    | '/client/search'
    | '/client/tenders'
    | '/ops/bookings'
    | '/ops/users'
    | '/organizations/branding'
    | '/organizations/members'
    | '/organizations/permissions'
    | '/organizations/'
    | '/client/book/$id'
    | '/client/providers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/activity-logs'
    | '/ai-assistant'
    | '/ai-automations'
    | '/ai-conversations'
    | '/audit-logs'
    | '/bookings'
    | '/clients'
    | '/contractors'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/jobs'
    | '/notifications'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/tasks'
    | '/workflows'
    | '/invite/$token'
    | '/client/ai-match'
    | '/client/bookings'
    | '/client/calendar'
    | '/client/favorites'
    | '/client/messages'
    | '/client/profile'
    | '/client/search'
    | '/client/tenders'
    | '/ops/bookings'
    | '/ops/users'
    | '/organizations/branding'
    | '/organizations/members'
    | '/organizations/permissions'
    | '/organizations'
    | '/client/book/$id'
    | '/client/providers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/_authenticated/activity-logs'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/ai-automations'
    | '/_authenticated/ai-conversations'
    | '/_authenticated/audit-logs'
    | '/_authenticated/bookings'
    | '/_authenticated/clients'
    | '/_authenticated/contractors'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/jobs'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/subscriptions'
    | '/_authenticated/tasks'
    | '/_authenticated/workflows'
    | '/invite/$token'
    | '/_authenticated/client/ai-match'
    | '/_authenticated/client/bookings'
    | '/_authenticated/client/calendar'
    | '/_authenticated/client/favorites'
    | '/_authenticated/client/messages'
    | '/_authenticated/client/profile'
    | '/_authenticated/client/search'
    | '/_authenticated/client/tenders'
    | '/_authenticated/ops/bookings'
    | '/_authenticated/ops/users'
    | '/_authenticated/organizations/branding'
    | '/_authenticated/organizations/members'
    | '/_authenticated/organizations/permissions'
    | '/_authenticated/organizations/'
    | '/_authenticated/client/book/$id'
    | '/_authenticated/client/providers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractors': {
      id: '/_authenticated/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof AuthenticatedContractorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-conversations': {
      id: '/_authenticated/ai-conversations'
      path: '/ai-conversations'
      fullPath: '/ai-conversations'
      preLoaderRoute: typeof AuthenticatedAiConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-automations': {
      id: '/_authenticated/ai-automations'
      path: '/ai-automations'
      fullPath: '/ai-automations'
      preLoaderRoute: typeof AuthenticatedAiAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-logs': {
      id: '/_authenticated/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/permissions': {
      id: '/_authenticated/organizations/permissions'
      path: '/organizations/permissions'
      fullPath: '/organizations/permissions'
      preLoaderRoute: typeof AuthenticatedOrganizationsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/members': {
      id: '/_authenticated/organizations/members'
      path: '/organizations/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof AuthenticatedOrganizationsMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/branding': {
      id: '/_authenticated/organizations/branding'
      path: '/organizations/branding'
      fullPath: '/organizations/branding'
      preLoaderRoute: typeof AuthenticatedOrganizationsBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/users': {
      id: '/_authenticated/ops/users'
      path: '/ops/users'
      fullPath: '/ops/users'
      preLoaderRoute: typeof AuthenticatedOpsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/bookings': {
      id: '/_authenticated/ops/bookings'
      path: '/ops/bookings'
      fullPath: '/ops/bookings'
      preLoaderRoute: typeof AuthenticatedOpsBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/tenders': {
      id: '/_authenticated/client/tenders'
      path: '/client/tenders'
      fullPath: '/client/tenders'
      preLoaderRoute: typeof AuthenticatedClientTendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/search': {
      id: '/_authenticated/client/search'
      path: '/client/search'
      fullPath: '/client/search'
      preLoaderRoute: typeof AuthenticatedClientSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/profile': {
      id: '/_authenticated/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof AuthenticatedClientProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/messages': {
      id: '/_authenticated/client/messages'
      path: '/client/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof AuthenticatedClientMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/favorites': {
      id: '/_authenticated/client/favorites'
      path: '/client/favorites'
      fullPath: '/client/favorites'
      preLoaderRoute: typeof AuthenticatedClientFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/calendar': {
      id: '/_authenticated/client/calendar'
      path: '/client/calendar'
      fullPath: '/client/calendar'
      preLoaderRoute: typeof AuthenticatedClientCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/bookings': {
      id: '/_authenticated/client/bookings'
      path: '/client/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof AuthenticatedClientBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/ai-match': {
      id: '/_authenticated/client/ai-match'
      path: '/client/ai-match'
      fullPath: '/client/ai-match'
      preLoaderRoute: typeof AuthenticatedClientAiMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/providers/$id': {
      id: '/_authenticated/client/providers/$id'
      path: '/client/providers/$id'
      fullPath: '/client/providers/$id'
      preLoaderRoute: typeof AuthenticatedClientProvidersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/book/$id': {
      id: '/_authenticated/client/book/$id'
      path: '/client/book/$id'
      fullPath: '/client/book/$id'
      preLoaderRoute: typeof AuthenticatedClientBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogsRoute: typeof AuthenticatedActivityLogsRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAiAutomationsRoute: typeof AuthenticatedAiAutomationsRoute
  AuthenticatedAiConversationsRoute: typeof AuthenticatedAiConversationsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedContractorsRoute: typeof AuthenticatedContractorsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedClientAiMatchRoute: typeof AuthenticatedClientAiMatchRoute
  AuthenticatedClientBookingsRoute: typeof AuthenticatedClientBookingsRoute
  AuthenticatedClientCalendarRoute: typeof AuthenticatedClientCalendarRoute
  AuthenticatedClientFavoritesRoute: typeof AuthenticatedClientFavoritesRoute
  AuthenticatedClientMessagesRoute: typeof AuthenticatedClientMessagesRoute
  AuthenticatedClientProfileRoute: typeof AuthenticatedClientProfileRoute
  AuthenticatedClientSearchRoute: typeof AuthenticatedClientSearchRoute
  AuthenticatedClientTendersRoute: typeof AuthenticatedClientTendersRoute
  AuthenticatedOpsBookingsRoute: typeof AuthenticatedOpsBookingsRoute
  AuthenticatedOpsUsersRoute: typeof AuthenticatedOpsUsersRoute
  AuthenticatedOrganizationsBrandingRoute: typeof AuthenticatedOrganizationsBrandingRoute
  AuthenticatedOrganizationsMembersRoute: typeof AuthenticatedOrganizationsMembersRoute
  AuthenticatedOrganizationsPermissionsRoute: typeof AuthenticatedOrganizationsPermissionsRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedClientBookIdRoute: typeof AuthenticatedClientBookIdRoute
  AuthenticatedClientProvidersIdRoute: typeof AuthenticatedClientProvidersIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogsRoute: AuthenticatedActivityLogsRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAiAutomationsRoute: AuthenticatedAiAutomationsRoute,
  AuthenticatedAiConversationsRoute: AuthenticatedAiConversationsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedContractorsRoute: AuthenticatedContractorsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedClientAiMatchRoute: AuthenticatedClientAiMatchRoute,
  AuthenticatedClientBookingsRoute: AuthenticatedClientBookingsRoute,
  AuthenticatedClientCalendarRoute: AuthenticatedClientCalendarRoute,
  AuthenticatedClientFavoritesRoute: AuthenticatedClientFavoritesRoute,
  AuthenticatedClientMessagesRoute: AuthenticatedClientMessagesRoute,
  AuthenticatedClientProfileRoute: AuthenticatedClientProfileRoute,
  AuthenticatedClientSearchRoute: AuthenticatedClientSearchRoute,
  AuthenticatedClientTendersRoute: AuthenticatedClientTendersRoute,
  AuthenticatedOpsBookingsRoute: AuthenticatedOpsBookingsRoute,
  AuthenticatedOpsUsersRoute: AuthenticatedOpsUsersRoute,
  AuthenticatedOrganizationsBrandingRoute:
    AuthenticatedOrganizationsBrandingRoute,
  AuthenticatedOrganizationsMembersRoute:
    AuthenticatedOrganizationsMembersRoute,
  AuthenticatedOrganizationsPermissionsRoute:
    AuthenticatedOrganizationsPermissionsRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedClientBookIdRoute: AuthenticatedClientBookIdRoute,
  AuthenticatedClientProvidersIdRoute: AuthenticatedClientProvidersIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
